-------------------------
-- Czech Localization String resources
-- miuios.cz (2014)
-- kynio
-------------------------
localization_Czech_table = {
    calories_table={
	{str="≈ Okurek (100g)", calories=14}, 
	{str="≈ Kuřecí vývar (100g)", calories=15}, 
	{str="≈ Kapusta (100g)", calories=16}, 
	{str="≈ Nakládaná rajčata (100g)", calories=19}, 
	{str="≈ Houby (100g)", calories=20}, 
	{str="≈ Ředkvičky (100g)", calories=21}, 
	{str="≈ Baklažán (100g)", calories=24}, 
	{str="≈ Dýně (100g)", calories=25}, 
	{str="≈ Kyselá kapusta (100g)", calories=25}, 
	{str="≈ Houbová polévka (100g)", calories=26}, 
	{str="≈ Brokolice (100g)", calories=27}, 
	{str="≈ Zeleninová polévka (100g)", calories=28}, 
	{str="≈ Jahody (100g)", calories=30}, 
	{str="≈ Boršč (100g)", calories=36}, 
	{str="≈ Masová polévka (100g)", calories=36}, 
	{str="≈ Červená řepa (100g)", calories=36}, 
	{str="≈ Jablka (100g)", calories=37}, 
	{str="≈ Pomeranč (100g)", calories=38}, 
	{str="≈ Bramborová polévka (100g)", calories=39}, 
	{str="≈ Meloun (100g)", calories=39}, 
	{str="≈ Šťavelová polévka (100g)", calories=40}, 
	{str="≈ Cmar 1% (100g)", calories=40}, 
	{str="≈ Coca-Cola (100g)", calories=42}, 
	{str="≈ 1,5% mléko (100g)", calories=45}, 
	{str="≈ Red Bull (100g)", calories=45}, 
	{str="≈ Polévka (100g)", calories=46}, 
	{str="≈ Broskev (100g)", calories=46}, 
	{str="≈ Sýr (25g)", calories=48}, 
	{str="≈ Třešně (100g)", calories=52}, 
	{str="≈ Pomerančový džus (100g)", calories=54}, 
	{str="≈ 3,2% mléko (100g)", calories=58}, 
	{str="≈ Ratatouille (100g)", calories=60}, 
	{str="≈ Bramborová kaše (100g)", calories=65}, 
	{str="≈ Hrachová polévka (100g)", calories=66}, 
	{str="≈ Mango (100g)", calories=67}, 
	{str="≈ Čočková polévka (100g)", calories=68}, 
	{str="≈ Jahodové želé (100g)", calories=69}, 
	{str="≈ Jogurt 1,5% (100g)", calories=70}, 
	{str="≈ Krabí tyčinky (100g)", calories=73}, 
	{str="≈ Squid (100g)", calories=75}, 
	{str="≈ Champagne (100g)", calories=76}, 
	{str="≈ Víno 13% (100g)", calories=78}, 
	{str="≈ Kapustový guláš (100g)", calories=81}, 
	{str="≈ Vařené brambory (100g)", calories=82}, 
	{str="≈ Absinthe 60% (100g)", calories=83}, 
	{str="≈ Bramborová kaše s mlékem (100g)", calories=85}, 
	{str="≈ Vařená vejce (55g)", calories=88}, 
	{str="≈ Banán (100g)", calories=89}, 
	{str="≈ Rajčatová fazole (100g)", calories=92}, 
	{str="≈ Kečup (100g)", calories=93}, 
	{str="≈ Rýže se zeleninou (100g)", calories=94}, 
	{str="≈ Toast (1 plátek)", calories=95}, 
	{str="≈ Tuňák (100g)", calories=96}, 
	{str="≈ Vařené walleye (100g)", calories=97}, 
	{str="≈ Zeleninový guláš (100g)", calories=99}, 
	{str="≈ Vařený kapr (100g)", calories=102}, 
	{str="≈ Ovocný salát (100g)", calories=103}, 
	{str="≈ Filet krocana (100g)", calories=104}, 
	{str="≈ Uzený jeseter (100g)", calories=105}, 
	{str="≈ Rýže (100g)", calories=113}, 
	{str="≈ Zeppelins (100g)", calories=117}, 
	{str="≈ Míchaná vejce", calories=119}, 
	{str="≈ Kaviár z kabačku (100g)", calories=122}, 
	{str="≈ Japonská majonéza (100g)", calories=134}, 
	{str="≈ Marshmallow (1ks)", calories=135},
	{str="≈ Cottage sýr (100g)", calories=136}, 
	{str="≈ Avocado", calories=140}, 
	{str="≈ Cappuccino (100g)", calories=140}, 
	{str="≈ Lobi (100g)", calories=141}, 
	{str="≈ Hovězí jazyk (100g)", calories=146}, 
	{str="≈ Hovězí guláš (100g)", calories=148}, 
	{str="≈ Vařený kuřecí řízek (100g)", calories=153}, 
	{str="≈ Smažené brambory (100g)", calories=154}, 
	{str="≈ Pizza Margarita (100g)", calories=157}, 
	{str="≈ Karbanátky (100g)", calories=159}, 
	{str="≈ Pohanka (100g)", calories=160}, 
	{str="≈ Žitný chléb (100g)", calories=165}, 
	{str="≈ Pečený krocan (100g)", calories=165}, 
	{str="≈ Uzené kuřecí (100g)", calories=184}, 
	{str="≈ Vepřové maso (100g)", calories=195}, 
	{str="≈ Klobása (100g)", calories=198},
	{str="≈ Losos (200g)", calories=201}, 
	{str="≈ Smetana 20% (100g)", calories=204}, 
	{str="≈ Krém (100g)", calories=206}, 
	{str="≈ Pasta Bolognese (100g)", calories=208}, 
	{str="≈ Černý chléb (100g)", calories=214}, 
	{str="≈ Kandované ovoce (100g)", calories=216}, 
	{str="≈ Slaneček (100g)", calories=217}, 
	{str="≈ Mushroom julienne (100g)", calories=219}, 
	{str="≈ Caesar salát (100g)", calories=221}, 
	{str="≈ Omeleta (100g)", calories=222}, 
	{str="≈ Světlé pivo (0,5l)", calories=225}, 
	{str="≈ Ovesný chléb (100g)", calories=226}, 
	{str="≈ Dušené jehněčí (100g)", calories=226}, 
	{str="≈ Sundae (100g)", calories=227}, 
	{str="≈ McD Hamburger", calories=229}, 
	{str="≈ Pečené vepřové (100g)", calories=233}, 
	{str="≈ Bílý chléb (100g)", calories=235}, 
	{str="≈ Pita chléb (100g)", calories=236}, 
	{str="≈ Vodka 40% (100g)", calories=237}, 
	{str="≈ Basturma (100g)", calories=240}, 
	{str="≈ Šunka italská (100g)", calories=241}, 
	{str="≈ Ravioli (100g)", calories=245}, 
	{str="≈ Červený kaviár (100g)", calories=249}, 
	{str="≈ Shawarma (100g)", calories=250}, 
	{str="≈ Kuřecí párky (100g)", calories=259}, 
	{str="≈ Karbanátky (100g)", calories=260}, 
	{str="≈ Rozinky (100g)", calories=262}, 
	{str="≈ McD Cheeseburger", calories=264}, 
	{str="≈ Klobásy (100g)", calories=270}, 
	{str="≈ Šunka (100g)", calories=270}, 
	{str="≈ Huňáčik uzený (100g)", calories=270}, 
	{str="≈ McD McNuggets (100g)", calories=272}, 
	{str="≈ Knedlík (100g)", calories=275}, 
	{str="≈ Grilovaný losos (100g)", calories=283}, 
	{str="≈ Černý kaviár (100g)", calories=289}, 
	{str="≈ Majonéza (100g)", calories=299}, 
	{str="≈ Med (100g)", calories=302}, 
	{str="≈ McD hranolky (100g)", calories=303}, 
	{str="≈ Termíny (100g)", calories=306}, 
	{str="≈ Jablečné palačinky (100g)", calories=306}, 
	{str="≈ Plněná kapusta (100g)", calories=311}, 
	{str="≈ Palačinky (100g)", calories=322}, 
	{str="≈ Omeleta se sýrem (100g)", calories=324}, 
	{str="≈ Játrový salám (100g)", calories=326}, 
	{str="≈ Šišky (100g)", calories=329}, 
	{str="≈ Cheesecake (100g)", calories=331}, 
	{str="≈ Lívance (100g)", calories=332}, 
	{str="≈ Kebab (100g)", calories=339}, 
	{str="≈ Špagety (100g)", calories=344}, 
	{str="≈ Muffin (100g)", calories=345}, 
	{str="≈ Perník (100g)", calories=350}, 
	{str="≈ Hovězí Stroganov (100g)", calories=355}, 
	{str="≈ Cornflakes (100g)", calories=363}, 
	{str="≈ Těstoviny (100g)", calories=371}, 
	{str="≈ Steak (100g)", calories=384}, 
	{str="≈ Suchary (100g)", calories=386}, 
	{str="≈ Cukr (100g)", calories=398}, 
	{str="≈ Ovesné sušenky (100g)", calories=440}, 
	{str="≈ Řízek (100g)", calories=456}, 
	{str="≈ Lasagne (100g)", calories=460}, 
	{str="≈ Foie gras (100g)", calories=462}, 
	{str="≈ Medovník (100g)", calories=478}, 
	{str="≈ Pop-corn (100g)", calories=480}, 
	{str="≈ Twix", calories=483}, 
	{str="≈ Snickers", calories=497}, 
	{str="≈ Slanina (100g)", calories=500}, 
	{str="≈ McD Big Mac", calories=510}, 
	{str="≈ Lays Max čipsy (100g)", calories=510}, 
	{str="≈ KitKat", calories=524}, 
	{str="≈ Tiramisu (100g)", calories=540}, 
	{str="≈ Pringles (100g)", calories=540}, 
	{str="≈ Čokoláda (100g)", calories=546}, 
	{str="≈ Napoleon torta (100g)", calories=552}, 
	{str="≈ Salám (100g)", calories=568}, 
	{str="≈ Pečená husa (100g)", calories=620}, 
	{str="≈ Smažený knedlík (100g)", calories=764}, 
	{str="≈ McD Big Tasty", calories=850}, 
    },

    ok='OK',

    hour='hod',
    minute='min',
    month='měsíc',
    day='den',
    step="krok",
    km='km',
    minute_format='%dmin',
    hour_minute_format='%dh %dm',
    hour_format='%dh',

    welcome_use="Vítejte :)",
    last_week_walked_format='Minulý týden jste ušli %d kroků',
    last_week_walked_info_format='Ušli jste %d km a spálili %d kcal',
    last_month_walked_format='Minulý měsíc jste ušli %d kroků',
    last_month_walked_info_format='Ušli jste %d km a spálili %d kcal',

    get_over_format=", kolem %dg tuku",
    click_to_get_help="Mrkněte co dokáže MiBand",
    take_a_walk="Projděte se s MiBand",
    take_a_walk_info="MiBand bude zaznamenávat vaši aktivitu a pomůže vám být fit.",
    unlock_hint="Odemkněte váš telefon s MiBand,",
    unlock_hint_info="Objevte nový způsob ochrany vašeho soukromí.",
    no_data_hint_0="Hýbejte se a sportujte pro vaše zdraví.",
    no_data_hint_1="Chcete být stále šťastní? Zaběhejte si.",
    no_data_hint_2="Kardio cvičení vás osvěží a rozhýbe každý den! ",
    no_data_hint_3="Běžný dospělý člověk stráví 15-20% spánku v hluboké fázi. ",
    not_binded_hint="Nemáte propojený MiBand s tímto účtem, propojte jej nyní. ",
    new_record_info="WoW! Právě byl zdolán rekord v chůzi.",
    new_record_format="Nový rekord, %d kroků, %s %d",
    today_goal_reached="Gratulujeme! Byl dosažen váš dnešní cíl. ",
    week_continue_reach_goal="Za poslední týden byl každý den splněn váš cíl! Skvělý týden!",
    challenge_format="Byl dosažen váš %d denní cíl!",
    personal_best_format="Váš nejvyšší rekord je %d dní!",
    active_time_format_0="%dmin",
    active_time_format_1="%dh",
    active_time_format_2="%dh %dmin",
    activie_run_format_0="Uběhli jste %s. Skvělé!",
    activie_run_format_1="Uběhli jste %s. Jen tak dál!",
    activie_run_format_2="Uběhli jste %s, Neskutečné!",
    activie_run_consumed="Spálili jste %d kcal. %s",
    continue_with_skips_title="Včera nebyl dosažen váš cíl. Celkem lenivý den ;)",
    continue_with_skips_title_today="Dnes nebyl dosažen váš cíl. Celkem odpočinkový den ;)",
    personal_best_with_skips_format="Máte už jen %d odpočinkových dní ;)",
    continue_used_n_skips_format="Byl dosažen váš cíl pro %d dní po sobě! Stále máte %d odpočinkových dní ;)",
    continue_used_0_skips_format="Byl dosažen váš cíl pro %d dní po sobě! Bez jediného odpočinkového dne.",
    personal_best_on_skip_day_title="%d denní rekord! Máte nárok na odpočinkový den!",
    personal_best_on_skip_day_info="Po každém 7-denním dosažení cíle, máte nárok na jeden odpočinkový den.",
    manual_lazy_title="Dnes nebyl dosažen váš cíl, chcete ho nazvat odpočinkovým dnem?",
    manual_lazy_subtitle="The streak will cover up if you confirm.",
    manual_lazy_title_used="Dnes je odpočinkový den, užijte si ho!",
    manual_lazy_subtitle_used="The streak will be added one if you hit the goal later.",
    manual_fail_ytd_title = "Sorry, the streak broken yesterday.",
    manual_fail_ytd_subtitle = "Your streak until day before yesterday is %d.",

    get_distance_format="celkem %dm",
    activity_walk_format="%s Chůze %d kroků %s",
    activity_walk_consumed_format="Spáleno %d kcal %s",

    activity_rope_skipping_format="%s přeskočeno švihadlo %d krát",
    activity_situp_format="%s %d sed-leh",
    activity_consumed_format="Spáleno %dkcal %s",
    activity_activity_format="%s %s v pohybu, %s",
    activity_activity_format_run="%s Cvičení %s, běhání %s",
    last_night_sleeped_good_format="Minulou noc trval spánek %s",
    last_night_sleeped_normal_format="Minulou noc trval spánek %s",
    deep_sleep_format="Hluboká fáze spánku trvala %s",

    battery_low_info="Baterie je vybitá, připojte MiBand na nabíječku.",
    battery_very_low_info="Připojte na nabíječku",

    cannot_find_bracelet="Nebylo možné najít váš MiBand?",
    cannot_find_bracelet_info="Ujistěte se, že váš MiBand je nabitý a nachází se v blízkosti vašeho telefonu.",
    challenge_to_get="%s dní od nového rekordu!",
    record_reach_max="Byl dosažen váš rekord!",
    new_record_born="Nový rekord!",
 }
