-------------------------
-- Czech Localization String resources
-- miuios.cz (2014)
-- kynio
-------------------------
localization_Czech_table = {
    calories_table={
        {str=" ",	calories=96},
        {str=" ",	calories=100},
        {str=" ",	calories=112},
        {str=" ",	calories=118},
        {str=" ",	calories=124},
        {str=" ",	calories=153},
        {str=" ",	calories=186},
        {str=" ",	calories=192},
        {str=" ",	calories=200},
        {str=" ",	calories=210},
        {str=" ",	calories=221},
        {str=" ",	calories=223},
        {str=" ",	calories=224},
        {str=" ",	calories=224},
        {str=" ",	calories=224},
        {str=" ",	calories=236},
        {str=" ",	calories=248},
        {str=" ",	calories=260},
        {str=" ",	calories=270},
        {str=" ",	calories=272},
        {str=" ",	calories=288},
        {str=" ",	calories=290},
        {str=" ",	calories=300},
        {str=" ",	calories=306},
        {str=" ",	calories=328},
        {str=" ",	calories=354},
        {str=" ",	calories=375},
        {str=" ",	calories=400},
        {str=" ",	calories=402},
        {str=" ",	calories=420},
        {str=" ",	calories=442},
        {str=" ",	calories=446},
        {str=" ",	calories=448},
        {str=" ",	calories=470},
        {str=" ",	calories=500},
        {str=" ",	calories=516},
        {str=" ",	calories=520},
        {str=" ",	calories=540},
        {str=" ",	calories=544},
        {str=" ",	calories=580},
        {str=" ",	calories=581},
        {str=" ",	calories=593},
        {str=" ",	calories=620},
        {str=" ",	calories=630},
        {str=" ",	calories=663},
        {str=" ",	calories=750},
        {str=" ",	calories=810},
        {str=" ",	calories=816},
    },

    ok='OK',

    hour='hod',
    minute='min',
    month='měsíc',
    day='den',
    step="krok",
    km='km',
    minute_format='%d min',
    hour_minute_format='%dh %dm',
    hour_format='%d h',

    welcome_use="Vítejte, já jsem váš MiBand.",
    last_week_walked_format='Minulý týden jste ušli %d kroků',
    last_week_walked_info_format='Ušli jste %d km a spálili %d cal',
    last_month_walked_format='Minulý měsíc jste ušli %d kroků',
    last_month_walked_info_format='Ušli jste %d km a spálili %d cal',

    get_over_format=", kolem %dg tuku",
    click_to_get_help="Mrkněte co dokáže MiBand",
    take_a_walk="Projděte se s MiBand",
    take_a_walk_info="MiBand bude zaznamenávat vaší aktivitu a pomůže vám být fit.",
    unlock_hint="Odemkněte váš telefon s MiBand,",
    unlock_hint_info="Objevte nový způsob ochrany vašeho soukromí.",
    no_data_hint_0="Hýbejte se a sportujte pro vaše zdraví.",
    no_data_hint_1="Chcete být stále šťastní? Zaběhejte si.",
    no_data_hint_2="Kardio cvičení vás osvěží a rozhýbe každý den! ",
    no_data_hint_3="Běžný dospělý člověk stráví 15-20% spánku v hluboké fázi. ",
    not_binded_hint="Nemáte propojený MiBand s tímto účtem, propojte jej nyní. ",
    new_record_info="WoW! Právě byl zdolán rekord v chůzi.",
    new_record_format="Nový rekord, %d kroků, %s %d",
    today_goal_reached="Gratulujeme! Byl dosažen váš dnešní cíl. ",
    week_continue_reach_goal="Za poslední týden byl každý den splněn váš cíl! Skvělý týden!",
    challenge_format="Byl dosažen váš %d denní cíl!",
    personal_best_format="Váš nejvyšší rekord je %d dní!",
    active_time_format_0="%dmin",
    active_time_format_1="%dh",
    active_time_format_2="%dh %dmin",
    activie_run_format_0="Uběhli jste %s. Skvělé!",
    activie_run_format_1="Uběhli jste %s. Jen tak dál!",
    activie_run_format_2="Uběhli jste %s, Neskutečné!",
    activie_run_consumed="Spálili jste %d cal. %s",

    get_distance_format=", celkem %dm",
    activity_walk_format="%s Chůze %d kroků %s",
    activity_walk_consumed_format="Spálené %d cal %s",

    activity_activity_format="%s %s v pohybu %s",
    last_night_sleeped_good_format="Minulou noc trval spánek %s",
    last_night_sleeped_normal_format="Minulou noc trval spánek %s",
    deep_sleep_format="Hluboká fáze spánku trvala %s",

    battery_low_info="Baterie je vybitá, připojte MiBand na nabíječku.",
    battery_very_low_info="Připojte na nabíječku",

    cannot_find_bracelet="Nebylo možné najít váš MiBand?",
    cannot_find_bracelet_info="Ujistěte se, že váš MiBand je nabitý a nachází se v blízkosti vašeho telefonu.",
    challenge_to_get="%s dní od nového rekordu!",
    record_reach_max="Byl dosažen váš rekord!",
    new_record_born="Nový rekord!",
 }

 
