-------------------------
-- Czech Localization String resources
-- miui.cz (2014)
-- kynio
-------------------------
localization_Czech_table = {
    calories_table={
        {str="≈1 duo z vařenách vajec",	calories=96},
        {str="≈1 krajíc chleba",	calories=100},
        {str="≈1 ledový čaj",	calories=112},
        {str="≈1 omeleta",	calories=118},
        {str="≈2 masa na špejli",	calories=124},
        {str="≈1 plechovka Coca-Cola",	calories=153},
        {str="≈3 masa na špejli",	calories=186},
        {str="≈2 duo z vařených vajec",	calories=192},
        {str="≈2 krajíce chleba",	calories=200},
        {str="≈1 miska rýže",	calories=210},
        {str="≈1 chleba",	calories=221},
        {str="≈1 balíček cukroví",	calories=223},
        {str="≈2 plechovky ledového čaje",	calories=224},
        {str="≈1 malé hranolky",	calories=224},
        {str="≈1 tartelette",	calories=224},
        {str="≈2 omelety",	calories=236},
        {str="≈4 masa na špejli",	calories=248},
        {str="≈1 hamburger",	calories=260},
        {str="≈1 koblih",	calories=270},
        {str="≈1 sekaná",	calories=272},
        {str="≈3 duo z vařených vajec",	calories=288},
        {str="≈1 kornout",	calories=290},
        {str="≈3 krajíce chleba",	calories=300},
        {str="≈2 plechovky Coca-Cola",	calories=306},
        {str="≈1 střední hranolky",	calories=328},
        {str="≈3 omelety",	calories=354},
        {str="≈1 tartelette s vajíčkem",	calories=375},
        {str="≈4 krajíce chleba",	calories=400},
        {str="≈1 velké hranolky",	calories=402},
        {str="≈2 bols de riz",	calories=420},
        {str="≈2 bagety",	calories=442},
        {str="≈2 balíčky Dragibus",	calories=446},
        {str="≈2 tartelette",	calories=448},
        {str="≈1 instantní nudle",	calories=470},
        {str="≈5 krajíců chleba",	calories=500},
        {str="≈1 smažené rizoto",	calories=516},
        {str="≈2 hamburgery",	calories=520},
        {str="≈2 buchty",	calories=540},
        {str="≈2 petits pains de viande",	calories=544},
        {str="≈2 kornoutky",	calories=580},
        {str="≈1 bol de nouilles instantanées",	calories=581},
        {str="≈1 bol de nouilles au boeuf",	calories=593},
        {str="≈10 mas na šmejli",	calories=620},
        {str="≈3 bols de riz",	calories=630},
        {str="≈3 pains",	calories=663},
        {str="≈2 tartelettes aux œufs",	calories=750},
        {str="≈3 koblihy",	calories=810},
        {str="≈3 petits pains de viande",	calories=816},
    },

    ok='OK',

    hour='hod',
    minute='min',
    month='měsíc',
    day='den',
    step="krok",
    km='km',
    minute_format='%d min',
    hour_minute_format='%dh %dm',
    hour_format='%d h',

    welcome_use="Vítejte, já jsem váš MiBand.",
    last_week_walked_format='Minulý týden jste ušli %d kroků',
    last_week_walked_info_format='Ušli jste %d km a spálili %d cal',
    last_month_walked_format='Minulý měsíc jste ušli %d kroků',
    last_month_walked_info_format='Ušli jste %d km a spálili %d cal',

    get_over_format=", kolem %dg tuku",
    click_to_get_help="Mrkněte co dokáže MiBand",
    take_a_walk="Projděte se s MiBand",
    take_a_walk_info="MiBand bude zaznamenávat vaší aktivitu a pomůže vám být zdravější.",
    unlock_hint="Odemkněte váš telefon s MiBand,",
    unlock_hint_info="Objevte nový způsob ochrany vašeho soukromí.",
    no_data_hint_0="Hýbejte se a sportujte pro vaše zdraví.",
    no_data_hint_1="Chcete být stále šťastní? Zaběhejte si.",
    no_data_hint_2="Kardio cvičení vás osvěží a rozhýbe každý den! ",
    no_data_hint_3="Běžný dospělý člověk stráví 15%-20% spánku v hluboké fázi. ",
    not_binded_hint="Nemáte propojený MiBand s tímto účtem, propojte jej nyní. ",
    new_record_info="WoW! Právě byl zdolán rekord v chůzi.",
    new_record_format="Nový rekord, %d kroků, %s %d",
    today_goal_reached="Gratulujeme! Byl dosažen váš dnešní cíl. ",
    week_continue_reach_goal="Za poslední týden byl každý den splněn váš cíl! Byl to skvělý týden!",
    challenge_format="Byl dosažen váš cíl pro %d dní!",
    personal_best_format="Váš nejvyšší rekord je %d dní!",
    active_time_format_0="%dh",
    active_time_format_1="%dh",
    active_time_format_2="%dh %dmin",
    activie_run_format_0="Uběhli jste %s. Skvělé!",
    activie_run_format_1="Uběhli jste %s. Jen tak dál!",
    activie_run_format_2="Uběhli jste %s, Neskutečné!",
    activie_run_consumed="Uběhli jste %d cal. %s",

    get_distance_format=", celkem %dm",
    activity_walk_format="%s Chůze %d kroků %s",
    activity_walk_consumed_format="Spálené %d cal %s",

    activity_activity_format="%s %s v pohybu %s",
    last_night_sleeped_good_format="Minulou noc trval spánek %dh %dmin. Skvělý spánek!",
    last_night_sleeped_normal_format="Minulou noc trval spánek %dh %dmin",
    deep_sleep_format="Hluboká fáze spánku trvala %dh %dmin",

    battery_low_info="Baterie je vybitá, připojte MiBand na nabíječku.",
    battery_very_low_info="Připojte na nabíječku",

    cannot_find_bracelet="Nebylo možné najít váš MiBand?",
    cannot_find_bracelet_info="Ujistěte se, že váš MiBand je nabitý a nachází se v blízkosti vašeho telefonu.",
    challenge_to_get="%s dní od nového rekordu!",
    record_reach_max="Byl dosažen váš rekord!",
    new_record_born="Nový rekord!",
 }
